attendance:
  cookie: "BAhbB2kCdAFJIiU3ZTMxMGNkNjg5ZDE4ZGIyZTdiZmZhMzgxMWIyZjExNgY6BkVU--947e6144da8548c0ac22f43220feb6a33af7a9e0"
  domain: attendance.developonbox.ru/
trackstudio:
  endpoint: "http://ts.developonbox.ru/!/personalprofile/time/list_persons.rjs"
  userID: "ff8081814b013c91014b07627518628e"
  login: alexey.nabrodov
  password: ahW3jahm
weather:
  apiKey: bddbf374b57d9a80
  location: "ru/Vsevolozhsk"
pushbullet:
  apiKey: o.okLP977DFUYIiNuXS4NXJKLnsuotPSto
sparkfun:
  whereiam:
    publicKey: v0bq71xR1yty8VDdj7v0
    privateKey: aPKVmJgbJ6szr7qX1nBE
  room:
    publicKey: 1nlJWdO8moSz5odgzOv9
    privateKey: 0mDEpRa8zwikDBo7kbRP
steam:
  apiKey: 90B9CAB39D586E26412485E7E92D3613
  steamID: 76561198049930669
teamviewer:
  clientID: 82103-gKOjCtN2iqou2emciXeZ
  clientSecret: gKOjCtN2iqou2emciXeZ
  code: CN4oz0oU
  userID: u18478569
telegram:
  token: 245615570:AAFUMsNdmELHUUl7dDGlpooQpNAclDHXc1I
  chatID: 123790949
